remote_theme: im1eon/slate
title: One-shot Voice Conversion on Different Speech Representation with Adversarial Mutual Information Learning
description: Submmitted to INTERSPEECH2022
theme: jekyll-theme-cayman
